### ISSUE TITLE
Possible broken pop in listings 7.17 

### ISSUE THREAD

**Issue by hqx871** [anthonywilliams/ccia_code_samples#27]
Read the following pop code, I found there may be something wrong with <b>res=ptr->data.exchange(nullptr)</b>, which should be replaced something like <b>res=ptr->data.load()</b>.
```
    std::unique_ptr<T> pop()
    {
        counted_node_ptr old_head=head.load(std::memory_order_relaxed);
        for(;;)
        {
            increase_external_count(head,old_head);
            node* const ptr=old_head.ptr;
            if(ptr==tail.load().ptr)
            {
                ptr->release_ref();
                return std::unique_ptr<T>();
            }
            if(head.compare_exchange_strong(old_head,ptr->next))
            {
                T* const res=ptr->data.exchange(nullptr);
                free_external_counter(old_head);
                return std::unique_ptr<T>(res);
            }
            ptr->release_ref();
        }
    }
```

**Comment by hqx871** [comment]
<b>Listing7.21 pop() </b> <i>modified to allow helping on the push() side</i> may have the same problem

**Comment by anthonywilliams** [comment]
The `exchange` is deliberate. It ensures that the node no longer has a data value, so the returned `unique_ptr` is indeed the only pointer to the object.

**Comment by hqx871** [comment]
But the push method in <b>listings 7.16</b> as follow use <b>old_tail.ptr->data.compare_exchange_strong</b> to store new_data and change the tail to new tail (new_next) later. 
Maybe it will make a broken push just like Listing 7.15 <i> A (broken) first attempt at revising push</i>?  
For example, starting with a empty list and the head.ptr is same as tail.ptr, producer p1 and p2 reach push at the same time and get the same old_tail from the same tail after <b>increase_external_count</b>, if p1 does <b>old_tail.data->compare_exchange_strong</b> succeed and then change the tail to new tail (new_next). Meanwhile, consume c1 exchange the value of head, which is  just stored by p1 and the head.ptr is same as the old_tail.ptr of p2,  then p2 will find the value of it's old_tail is nullptr and does compare_exchange_strong succeed.
```
void push(T new_value)
    {
        std::unique_ptr<T> new_data(new T(new_value));
        counted_node_ptr new_next;
        new_next.ptr=new node;
        new_next.external_count=1;
        counted_node_ptr old_tail=tail.load();
        for(;;)
        {
            increase_external_count(tail,old_tail);
            T* old_data=nullptr;
            if(old_tail.ptr->data.compare_exchange_strong(
                   old_data,new_data.get()))
            {
                old_tail.ptr->next=new_next;
                old_tail=tail.exchange(new_next);
                free_external_counter(old_tail);
                new_data.release();
                break;
            }
            old_tail.ptr->release_ref();
        }
    }
```

**Comment by hqx871** [comment]
What you mean by <i>It ensures that the node no longer has a data value</i>?  The data type is atomic<T*>, not unique_ptr or shared_ptr, so let the atomic data keep value pointer may not cause ownership problem. Am I right?
