### ISSUE TITLE
#Listing 4.5: Double lock on mutex?

### ISSUE THREAD

**Issue by Mibu287** [anthonywilliams/ccia_code_samples#4]
```
    void wait_and_pop(T& value)
    {
        std::unique_lock<std::mutex> lk(mut);
        data_cond.wait(lk,[this]{return !data_queue.empty();});
        value=data_queue.front();
        data_queue.pop();
    }
```

```
    bool empty() const
    {
        std::lock_guard<std::mutex> lk(mut);
        return data_queue.empty();
    }
```

Class   `threadsafe_queue`'s `wait_for_lock` function lock on mutex and wait for predicate `empty()` to be false. However, calling of `empty()` require locking the mutex once more.

Does that lead to undefined behaviour due to double-locking of one mutex?

**Comment by rafal-c** [comment]
No, because you wait on `data_queue.empty()` which is `std::queue<T>::empty` and not `threadsafe_queue<T>::empty`. Only the latter locks the mutex.

**Comment by Mibu287** [comment]
@rafal-c Thanks for your response. You are correct.
